# Generated by Django 4.1.4 on 2022-12-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FotoPerfil', models.ImageField(upload_to='static/img/front', verbose_name='Foto de Perfil')),
                ('AcercaDe', models.TextField(help_text='Coloque algo acerca de Usted', verbose_name='Acerca de ti')),
                ('Puesto', models.CharField(max_length=150, verbose_name='Perfil del Puesto')),
                ('Cumpleaños', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('Direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('Mail', models.CharField(max_length=250, verbose_name='E-Mail')),
                ('Telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('Proposito', models.TextField(blank=True, help_text='Describa un logro a futuro', null=True, verbose_name='Metas')),
            ],
            options={
                'verbose_name': 'Acerca',
                'verbose_name_plural': 'Acerca de',
                'db_table': 'acerca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('Telefono', models.CharField(max_length=150, verbose_name='Telefono')),
                ('Correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('Mensaje', models.TextField(blank=True, help_text='Introduzca una su mensaje', null=True, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Introduccion', models.TextField(blank=True, help_text='Una introduccion de las experiencias laborales', null=True, verbose_name='experiencia laboral')),
                ('Empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('Puesto', models.CharField(max_length=150, verbose_name='Puesto')),
                ('FechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('FechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('Salario', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salario')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'db_table': 'experiencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lenguajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(blank=True, help_text='Una introduccion de los conocimientos de su lenguaje de programacion', null=True, verbose_name='Introduccion de Lenguajes')),
                ('lenguaje', models.CharField(max_length=150, verbose_name='Lenguaje')),
                ('Porcentaje', models.PositiveSmallIntegerField(verbose_name='Aprovechamiento')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'db_table': 'lenguaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(upload_to='static/img/portafolio')),
                ('Etiqueta', models.CharField(max_length=150, verbose_name='Etiqueta')),
                ('Descripcion', models.TextField(blank=True, help_text='Introduzca una descripcion', null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icono', models.CharField(choices=[('tiktok', 'tiktok'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('whatsapp', 'whatsapp'), ('linkedin', 'linkedin'), ('twitch', 'twitch'), ('pinterest', 'pinterest'), ('messenger', 'messenger')], max_length=150, verbose_name='Icono')),
                ('SocialMedia', models.URLField(verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
                'db_table': 'social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enfoque', models.TextField(blank=True, help_text='Una introduccion de sus enfoque de habilidades en Software', null=True, verbose_name='Software a usar')),
                ('Software', models.CharField(max_length=150, verbose_name='Software')),
                ('Porcentaje', models.PositiveSmallIntegerField(verbose_name='Aprovechamiento')),
            ],
            options={
                'verbose_name': 'Conocimiento',
                'verbose_name_plural': 'Conocimientos',
                'db_table': 'conocimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Profesiones', models.CharField(max_length=150, verbose_name='Profesiones')),
                ('PortadaFondo', models.ImageField(upload_to='static/img/front')),
                ('SocialM', models.ManyToManyField(to='cv.social')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'presentacion',
                'managed': True,
            },
        ),
    ]
