# Generated by Django 4.1.4 on 2022-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_acercade_proposito2'),
    ]

    operations = [
        migrations.AddField(
            model_name='acercade',
            name='Ubicacion',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
