# Generated by Django 4.1.4 on 2022-12-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_acercade_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercade',
            name='Ubicacion',
            field=models.URLField(blank=True, help_text='Coloque una Ubicaicon de su Domicilio, debe de ser aproximada. Nunca debe de colocar una ubicacion Excata', null=True, verbose_name='Unicación'),
        ),
    ]
