# Generated by Django 4.1.4 on 2022-12-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0004_alter_acercade_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acercade',
            name='Ubicacion',
            field=models.TextField(blank=True, help_text='Coloque una Ubicaicon de su Domicilio, debe de ser aproximada. Nunca debe de colocar una ubicacion Excata, en formato iframe', max_length=200, null=True, verbose_name='Unicación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Mensaje',
            field=models.TextField(help_text='Introduzca una su mensaje', verbose_name='Mensaje'),
        ),
    ]
